### ISSUE TITLE
New version of Pip available

### ISSUE THREAD

**Issue by taketwo** [pipxproject/pipx-app#72]
When I run `pipx upgrade-all` I get the following message once for every installed package:

```
You are using pip version 18.1, however version 19.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Perhaps _pipx_ should update _pip_ in each package's virtualenv?

**Comment by schinckel** [comment]
In the meantime:

`find ~/.local/pipx/venvs/*/bin -name pip -exec {} install pip --upgrade \;`

**Comment by schinckel** [comment]
But this does raise the question: should we be able to upgrade arbitrary injected packages/dependencies using `pipx upgrade <package>`?

**Comment by cs01** [comment]
pipx now upgrades pip when upgrading any pipx-installed package.

> But this does raise the question: should we be able to upgrade arbitrary injected packages/dependencies using pipx upgrade <package>?

Thanks for asking this. I think it should be discussed in a separate issue.

**Comment by danielhoherd** [comment]
I am still seeing problems with pip complaining about the version, even when there is no virtualenv for the tool being installed and pip is up to date.

```
$ pipx --version
0.12.1.0
$ pip2 --version
pip 19.0.2 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
$ pip3 --version
pip 19.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$ pipx list
nothing has been installed with pipx 😴
$ pipx install -e plexdl
--upgrade should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
You are using pip version 18.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
'/Users/dho/.local/pipx/venvs/plexdl/bin/python -m pip install --editable --upgrade pip -q' failed
```
