### ISSUE TITLE
Get pipx listed in Poetry installation methods instead of pipsi

### ISSUE THREAD

**Issue by taketwo** [pipxproject/pipx-app#84]
Poetry has a subsection in its [introduction](https://poetry.eustace.io/docs/) docs explaining how to install it with `pipsi`. It's under "Alternative installation methods (not recommended)", but still would be nice to advertise `pipx` there.

**Comment by cs01** [comment]
Thanks for the suggestion. I filed an issue and PR for this back in Nov. The author said he was open to adding pipx to installation instructions, but hasn't been very active on the project. My PR is still open (there are some PR's open from June of 2018). I also filed a PR with packaging.python.org to add pipx, and they are open to it too. We are holding off from merging there until after I finish the rename from pipx-app back to pipx on PyPI.

https://github.com/sdispater/poetry/issues/677
https://github.com/sdispater/poetry/pull/692

**Comment by cs01** [comment]
Just a note to anyone reading this -- please feel free to add pipx as an installation method to your project, or add PRs to other projects. Your PR is just as likely to get accepted as mine is 😄. You can also tag me too, as I would be happy to see them and I can chime in if necessary.

**Comment by taketwo** [comment]
Oops, should have checked open issues in poetry. Sorry for the noise :)
